name: CI

on:
  schedule:
  - cron: 0 7 * * *
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: npm install
      run: npm install
    - name: build
      run: npm run build
    - name: debug before deploy
      run: cd build; ls -lh; cd -
    - name: deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: contains(github.ref, 'master')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: ./build
        PUBLISH_BRANCH: gh-pages
    - name: debug after deploy
      run: cd build; ls -lh; cd -

