name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: npm install
      run: npm install
    - name: build
      run: npm run build
    - uses: peaceiris/actions-gh-pages@v1.1.0
      env:
        PUBLISH_DIR: ./build
        PUBLISH_BRANCH: gh-pages
      secrets: ["GITHUB_TOKEN"]
